// Additive L3 schema compiler. Existing owner contracts remain unchanged.
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { Ajv2020 } from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { build } from 'esbuild';
const paths = ['contracts/financial-research/v1/shared.schema.json', 'contracts/verified-claim/v1/claim.schema.json'];
const raw = paths.map(path => fs.readFileSync(path, 'utf8').replaceAll('\r\n', '\n'));
const ajv = new Ajv2020({ strict: true, strictRequired: false, ownProperties: true, code: { source: true, esm: true } });
addFormats(ajv);
raw.slice(0, -1).forEach(text => ajv.addSchema(JSON.parse(text)));
const validate = ajv.compile(JSON.parse(raw.at(-1)));
const built = await build({ stdin: { contents: standaloneCode(ajv, validate), resolveDir: process.cwd() }, bundle: true, write: false, minify: false, platform: 'browser', format: 'esm' });
const output = '// Generated by scripts/contracts/verified-claim.mjs; do not edit.\n// Schema SHA256: ' + raw.map(text => createHash('sha256').update(text).digest('hex')).join(' ') + '\n'
  + ['ajv', 'ajv-formats', 'fast-deep-equal'].map(name => `/*! ${name} runtime helper license\n${fs.readFileSync(`node_modules/${name}/LICENSE`, 'utf8')}\n*/\n`).join('') + built.outputFiles[0].text;
const target = 'src/services/verifiedClaimValidator.generated.mjs';
if (process.argv.includes('--write')) fs.writeFileSync(target, output);
else if (fs.readFileSync(target, 'utf8').replaceAll('\r\n', '\n') !== output) throw new Error('CLAIM_VALIDATOR_DRIFT');
console.log('Verified Claim V1 closed schema / standalone validator: PASS (no authority promotion).');
