import { describe, expect, it } from "vitest";
import type { EarningsExpectationSnapshot, ResearchEvent } from "../types";
import { compareEarningsExpectation } from "./earningsExpectationComparisonProvider";

describe("earnings expectation comparison", () => {
  it("37 compares a point estimate for the same report period", () => { const result = compareEarningsExpectation(snapshot(), [actual(120)]); expect(result.comparisonResult).toBe("above"); expect(result.absoluteDifference).toBe(20); expect(result.relativeDifference).toBeCloseTo(0.2); });
  it("38 classifies values above, within and below a range", () => { const range = { ...snapshot(), estimateShape: "range" as const, value: null, lowerBound: 90, upperBound: 110 }; expect(compareEarningsExpectation(range, [actual(120)]).comparisonResult).toBe("above"); expect(compareEarningsExpectation(range, [actual(100)]).comparisonResult).toBe("within"); expect(compareEarningsExpectation(range, [actual(80)]).comparisonResult).toBe("below"); });
  it("39 never mixes single-quarter and cumulative values", () => { const result = compareEarningsExpectation({ ...snapshot(), periodScope: "single_quarter" }, [actual(100, "cumulative")]); expect(result.comparabilityStatus).toBe("insufficient_data"); expect(result.nonComparableReasons).toContain("无法匹配实际值"); });
  it("40 never mixes annual and quarterly report periods", () => { const result = compareEarningsExpectation({ ...snapshot(), reportPeriod: "2026-12-31", periodScope: "full_year" }, [actual(100)]); expect(result.actualValue).toBeNull(); });
  it("41 standardizes supported units", () => { const result = compareEarningsExpectation({ ...snapshot(), value: 1, unit: "hundred_million_yuan" }, [actual(120_000_000)]); expect(result.expectedValue).toBe(100_000_000); expect(result.absoluteDifference).toBe(20_000_000); });
  it("42 marks unsupported currency conversion as non-comparable", () => { const result = compareEarningsExpectation({ ...snapshot(), currency: "HKD" }, [actual(120)]); expect(result.comparisonResult).toBe("not_comparable"); expect(result.nonComparableReasons).toContain("币种无法可靠换算"); });
  it("43 omits percentage difference when expected value is zero", () => { const result = compareEarningsExpectation({ ...snapshot(), value: 0 }, [actual(10)]); expect(result.relativeDifference).toBeNull(); expect(result.nonComparableReasons).toContain("预期值为0，百分比差异不适用"); });
  it("44 omits percentage difference near zero", () => { const result = compareEarningsExpectation({ ...snapshot(), value: 1e-10 }, [actual(2e-10)]); expect(result.relativeDifference).toBeNull(); expect(result.nonComparableReasons[0]).toContain("接近0"); });
  it("45 omits percentage difference across signs", () => { const result = compareEarningsExpectation({ ...snapshot(), value: -100 }, [actual(100)]); expect(result.relativeDifference).toBeNull(); expect(result.nonComparableReasons[0]).toContain("正负号跨越"); });
  it("46 recognizes a verified pre-disclosure snapshot as ex ante", () => expect(compareEarningsExpectation(snapshot(), [actual(120)]).isExAnte).toBe(true));
  it("47 treats a post-disclosure snapshot as ex-post reference only", () => { const result = compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-07-02" }, [actual(120)]); expect(result.isExAnte).toBe(false); expect(result.nonComparableReasons).toContain("预期形成日期晚于实际披露"); });
  it("48 keeps missing actual values as null instead of zero", () => { const result = compareEarningsExpectation(snapshot(), [actual(null)]); expect(result.actualValue).toBeNull(); expect(result.comparisonResult).toBe("insufficient_data"); });
  it("49 refuses partially parsed actual values", () => { const result = compareEarningsExpectation(snapshot(), [{ ...actual(120), verificationStatus: "partial", parseStatus: "parse_partial" }]); expect(result.comparabilityStatus).toBe("insufficient_data"); expect(result.nonComparableReasons).toContain("实际数据解析状态不足"); });
  it("50 reports all structural non-comparability reasons", () => { const result = compareEarningsExpectation({ ...snapshot(), currency: "USD", accountingBasis: "unknown", sourceVerificationStatus: "pending" }, [actual(120)]); expect(result.nonComparableReasons).toEqual(expect.arrayContaining(["币种无法可靠换算", "会计口径不同或不明确", "预期来源无法核验"])); });
  it("66 requires an external source publication date for ex-ante status", () => { const result = compareEarningsExpectation({ ...snapshot(), sourceCategory: "institution_single", sourceName: "测试证券", sourceTitle: "盈利预测", sourceUrl: "https://example.com/report", sourcePublishedAt: null }, [actual(120)]); expect(result.isExAnte).toBe(false); expect(result.nonComparableReasons).toContain("外部来源发布日期缺失"); });
});

function snapshot(): EarningsExpectationSnapshot { return { id: "s-1", stockId: "demo", market: "A股", reportPeriod: "2026-06-30", periodScope: "half_year", metric: "revenue", estimateShape: "point", value: 100, lowerBound: null, upperBound: null, currency: "CNY", unit: "yuan", accountingBasis: "PRC_GAAP", sourceCategory: "user_estimate", sourceName: "用户个人预测", sourceTitle: "", sourceUrl: null, sourcePublishedAt: null, asOfDate: "2026-06-01", analystCount: null, institutionCount: null, ingestionMethod: "manual", createdAt: "2026-06-01T00:00:00.000Z", createdBy: "local-user", sourceVerificationStatus: "verified", notes: null, correctsSnapshotId: null, schemaVersion: 1 }; }
function actual(value: number | null, periodBasis: "cumulative" | "single_quarter" = "cumulative"): ResearchEvent { return { id: "actual-1", stockId: "demo", stockName: "测试公司", stockCode: "000001.SZ", industryId: "tech", market: "A股", eventType: "financial_update", eventDate: "2026-07-01", publishedAt: "2026-07-01", reportPeriod: "2026-06-30", title: "财务更新", summary: "正式财务", sourceType: "financial_report", sourceName: "正式来源", sourceUrl: "https://example.com/actual", pdfUrl: null, verificationStatus: "verified", parseStatus: "not_applicable", materiality: "high", metrics: [{ key: periodBasis === "single_quarter" ? "singleQuarterOperatingRevenue" : "operatingRevenue", label: "营业收入", value, unit: "CNY", periodBasis, sourceAnnouncementId: null, sourceFinancialPeriod: "2026-06-30" }], relatedAnnouncementIds: [], relatedFinancialPeriod: "2026-06-30", reviewStatus: "not_required", reviewReasons: [], isRestated: false, updatedAt: "2026-07-01" }; }
