import { describe, expect, it } from "vitest";
import type { EarningsExpectationSnapshot, ResearchEvent } from "../types";
import { buildEarningsExpectationComparisons, compareEarningsExpectation, expectationRevision } from "./earningsExpectationComparisonProvider";

describe("earnings expectation comparison", () => {
  it("37 compares a point estimate for the same report period", () => { const result = compareEarningsExpectation(snapshot(), [actual(120)]); expect(result.comparisonResult).toBe("above"); expect(result.absoluteDifference).toBe(20); expect(result.relativeDifference).toBeCloseTo(0.2); });
  it("38 classifies values above, within and below a range", () => { const range = { ...snapshot(), estimateShape: "range" as const, value: null, lowerBound: 90, upperBound: 110 }; expect(compareEarningsExpectation(range, [actual(120)]).comparisonResult).toBe("above"); expect(compareEarningsExpectation(range, [actual(100)]).comparisonResult).toBe("within"); expect(compareEarningsExpectation(range, [actual(80)]).comparisonResult).toBe("below"); });
  it("39 never mixes single-quarter and cumulative values", () => { const result = compareEarningsExpectation({ ...snapshot(), periodScope: "single_quarter" }, [actual(100, "cumulative")]); expect(result.comparabilityStatus).toBe("insufficient_data"); expect(result.nonComparableReasons).toContain("无法匹配实际值"); });
  it("40 never mixes annual and quarterly report periods", () => { const result = compareEarningsExpectation({ ...snapshot(), reportPeriod: "2026-12-31", periodScope: "full_year" }, [actual(100)]); expect(result.actualValue).toBeNull(); });
  it("41 standardizes supported units", () => { const result = compareEarningsExpectation({ ...snapshot(), value: 1, unit: "hundred_million_yuan" }, [actual(120_000_000)]); expect(result.expectedValue).toBe(100_000_000); expect(result.absoluteDifference).toBe(20_000_000); });
  it("42 marks unsupported currency conversion as non-comparable", () => { const result = compareEarningsExpectation({ ...snapshot(), currency: "HKD" }, [actual(120)]); expect(result.comparisonResult).toBe("not_comparable"); expect(result.nonComparableReasons).toContain("币种无法可靠换算"); });
  it("43 omits percentage difference when expected value is zero", () => { const result = compareEarningsExpectation({ ...snapshot(), value: 0 }, [actual(10)]); expect(result.relativeDifference).toBeNull(); expect(result.nonComparableReasons).toContain("预期值为0，百分比差异不适用"); });
  it("44 omits percentage difference near zero", () => { const result = compareEarningsExpectation({ ...snapshot(), value: 1e-10 }, [actual(2e-10)]); expect(result.relativeDifference).toBeNull(); expect(result.nonComparableReasons[0]).toContain("接近0"); });
  it("45 omits percentage difference across signs", () => { const result = compareEarningsExpectation({ ...snapshot(), value: -100 }, [actual(100)]); expect(result.relativeDifference).toBeNull(); expect(result.nonComparableReasons[0]).toContain("正负号跨越"); });
  it("46 recognizes a verified pre-disclosure snapshot as ex ante", () => expect(compareEarningsExpectation(snapshot(), [actual(120)]).isExAnte).toBe(true));
  it("47 treats a post-disclosure snapshot as ex-post reference only", () => { const result = compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-07-02" }, [actual(120)]); expect(result.isExAnte).toBe(false); expect(result.nonComparableReasons.some((item) => item.includes("不早于"))).toBe(true); });
  it("48 keeps missing actual values as null instead of zero", () => { const result = compareEarningsExpectation(snapshot(), [actual(null)]); expect(result.actualValue).toBeNull(); expect(result.comparisonResult).toBe("insufficient_data"); });
  it("49 refuses partially parsed actual values without calling it non-disclosure", () => { const result = compareEarningsExpectation(snapshot(), [{ ...actual(120), verificationStatus: "partial", parseStatus: "parse_partial" }]); expect(result.comparabilityStatus).toBe("insufficient_data"); expect(result.nonComparableReasons).toContain("公司实际业绩披露已识别，但本地实际值缺失、口径不匹配或解析状态不足"); expect(result.comparisonMethod).toContain("实际值暂不可可靠比较"); });
  it("50 reports all structural non-comparability reasons", () => { const result = compareEarningsExpectation({ ...snapshot(), currency: "USD", accountingBasis: "unknown", sourceVerificationStatus: "pending" }, [actual(120)]); expect(result.nonComparableReasons).toEqual(expect.arrayContaining(["币种无法可靠换算", "会计口径不同或不明确", "预期来源无法核验"])); });
  it("66 requires an external source publication date for ex-ante status", () => { const result = compareEarningsExpectation({ ...snapshot(), sourceCategory: "institution_single", sourceName: "测试证券", sourceTitle: "盈利预测", sourceUrl: "https://example.com/report", sourcePublishedAt: null }, [actual(120)]); expect(result.isExAnte).toBe(false); expect(result.nonComparableReasons).toContain("外部来源发布日期缺失"); });
  it("77 accepts exact same-day formation only when it is strictly before exact disclosure", () => { const event = { ...actual(120), publishedAt: "2026-07-01T08:00:00.000Z" }; const early = compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-07-01", formedAt: "2026-07-01T07:00:00.000Z", formedAtPrecision: "datetime" }, [event]); const late = compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-07-01", formedAt: "2026-07-01T09:00:00.000Z", formedAtPrecision: "datetime" }, [event]); expect(early.isExAnte).toBe(true); expect(late.isExAnte).toBe(false); });
  it("78 treats same-day date-only records conservatively and never uses createdAt as formation time", () => { const event = { ...actual(120), publishedAt: "2026-07-01T08:00:00.000Z" }; expect(compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-07-01", formedAt: null, formedAtPrecision: "date" }, [event]).isExAnte).toBe(false); expect(compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-06-30", createdAt: "2026-07-10T00:00:00.000Z" }, [event]).isExAnte).toBe(true); });
  it("79 distinguishes the selected actual disclosure from earlier relevant performance information", () => { const preview = performancePreview("2026-06-15T08:00:00.000Z"); const result = compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-06-20" }, [preview, { ...actual(120), publishedAt: "2026-07-01T08:00:00.000Z" }]); expect(result.beforeActualDisclosure).toBe(true); expect(result.beforeAnyPerformanceDisclosure).toBe(false); expect(result.isExAnte).toBe(false); expect(result.performanceInformationCutoff).toBe("2026-06-15T08:00:00.000Z"); });
  it("80 ignores performance events for unrelated metrics when deriving the cutoff", () => { const unrelated = { ...performancePreview("2026-06-15T08:00:00.000Z"), metrics: [{ ...performancePreview("2026-06-15T08:00:00.000Z").metrics[0], key: "netProfitAttributableToParentForecastMidpoint" }] }; const result = compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-06-20" }, [unrelated, actual(120)]); expect(result.beforeAnyPerformanceDisclosure).toBe(true); expect(result.performanceInformationCutoff).toBe("2026-07-01"); });
  it("81 derives comparison availability from business timestamps and stays stable across recalculation times", () => { const event = { ...actual(120), publishedAt: "2026-07-01T08:00:00.000Z" }; const first = compareEarningsExpectation(snapshot(), [event], undefined, "2026-07-02T00:00:00.000Z"); const second = compareEarningsExpectation(snapshot(), [event], undefined, "2026-07-10T00:00:00.000Z"); expect(first.comparisonAvailableAt).toBe("2026-07-01T08:00:00.000Z"); expect(first.comparisonAvailableAt).toBe(second.comparisonAvailableAt); });
  it("82 never computes revision rates across currency, unit or accounting-basis corrections", () => { expect(expectationRevision({ ...snapshot(), unit: "hundred_million_yuan" }, snapshot()).magnitude).toBeNull(); expect(expectationRevision({ ...snapshot(), accountingBasis: "IFRS" }, snapshot()).magnitude).toBeNull(); });
  it("89 applies exact same-day timing to verified external source publication", () => { const event = { ...actual(120), publishedAt: "2026-07-01T08:00:00.000Z" }; const base = { ...snapshot(), sourceCategory: "institution_single" as const, sourceName: "测试证券", sourceTitle: "盈利预测", sourceUrl: "https://example.com/report", asOfDate: "2026-07-01", formedAt: "2026-07-01T07:00:00.000Z", formedAtPrecision: "datetime" as const, sourcePublishedAtPrecision: "datetime" as const }; expect(compareEarningsExpectation({ ...base, sourcePublishedAt: "2026-07-01T07:30:00.000Z" }, [event]).isExAnte).toBe(true); expect(compareEarningsExpectation({ ...base, sourcePublishedAt: "2026-07-01T08:30:00.000Z" }, [event]).isExAnte).toBe(false); });
  it("90 treats predictions before previews as ex ante and revisions before predictions as a cutoff", () => { const preview = performancePreview("2026-06-15T08:00:00.000Z"); const actualEvent = { ...actual(120), publishedAt: "2026-07-01T08:00:00.000Z" }; expect(compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-06-01" }, [preview, actualEvent]).beforeAnyPerformanceDisclosure).toBe(true); const revision = { ...preview, id: "revision-1", eventType: "earnings_preview_revision" as const }; expect(compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-06-20" }, [revision, actualEvent]).beforeAnyPerformanceDisclosure).toBe(false); });
  it("keeps actual-value comparison independent when same-day business-node order is uncertain", () => { const left = { ...snapshot(), id: "a", asOfDate: "2026-06-01" }; const right = { ...snapshot(), id: "z", asOfDate: "2026-06-01", value: 110 }; const results = buildEarningsExpectationComparisons([left, right], [actual(120)]); expect(results).toHaveLength(1); expect(results[0]).toMatchObject({ snapshotId: "z", businessOrderStatus: "uncertain", comparabilityStatus: "comparable", comparisonResult: "above", absoluteDifference: 10 }); expect(results[0].structuredWarningCodes).not.toContain("business_order_ambiguous"); });
  it("uses metadata-only formal reports as a public disclosure boundary without inventing an actual value", () => { const metadata = { ...actual(null), id: "metadata-formal", eventType: "periodic_report" as const, publishedAt: "2026-06-15", eventDate: "2026-06-15", verificationStatus: "metadata_only" as const, parseStatus: "metadata_only" as const, metrics: [], performanceDisclosureScope: "all_metrics" as const }; const result = compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-06-20" }, [metadata, actual(120)]); expect(result.performanceDisclosureTimingStatus).toBe("after"); expect(result.isExAnte).toBe(false); expect(result.comparabilityStatus).toBe("not_comparable"); });
  it("keeps null and parse-partial formal-report metrics as disclosure boundaries but not actual candidates", () => { for (const formal of [{ ...actual(null), id: "null-formal", eventType: "periodic_report" as const, performanceDisclosureScope: "all_metrics" as const }, { ...actual(null), id: "partial-formal", eventType: "periodic_report" as const, verificationStatus: "partial" as const, parseStatus: "parse_partial" as const, metrics: [], performanceDisclosureScope: "all_metrics" as const }]) { const result = compareEarningsExpectation(snapshot(), [formal]); expect(result.performanceInformationCutoff).toBe("2026-07-01"); expect(result.performanceDisclosureTimingStatus).toBe("before"); expect(result.actualValue).toBeNull(); expect(result.comparisonResult).toBe("insufficient_data"); } });
  it("treats parse-partial flash metadata as disclosed while keeping numeric comparison insufficient", () => { const partial = { ...actual(null), id: "partial-flash", eventType: "earnings_flash" as const, verificationStatus: "partial" as const, parseStatus: "parse_partial" as const, metrics: [], performanceDisclosureScope: "all_metrics" as const }; const result = compareEarningsExpectation(snapshot(), [partial]); expect(result.performanceInformationCutoff).toBe("2026-07-01"); expect(result.performanceDisclosureTimingStatus).toBe("before"); expect(result.comparisonResult).toBe("insufficient_data"); expect(result.actualValue).toBeNull(); });
  it("uses possible disclosure bounds only when they can prove the prediction was earlier than every boundary", () => { const metadataPreview = { ...performancePreview("2026-06-15T08:00:00.000Z"), metrics: [], verificationStatus: "metadata_only" as const, parseStatus: "metadata_only" as const, performanceDisclosureScope: "unknown" as const }; const early = compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-06-01" }, [metadataPreview, actual(120)]); expect(early.performanceDisclosureTimingStatus).toBe("before"); expect(early.performanceDisclosureUncertain).toBe(false); expect(early.isExAnte).toBe(true); const late = compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-06-20" }, [metadataPreview, actual(120)]); expect(late.performanceDisclosureTimingStatus).toBe("unknown"); expect(late.performanceDisclosureUncertain).toBe(true); expect(late.isExAnte).toBe(false); expect(late.comparabilityStatus).toBe("not_comparable"); });
  it("does not treat a local financial-summary refresh as disclosure or as a timed actual", () => { const refresh = { ...actual(100), id: "local-refresh", publishedAt: "2026-06-15", eventDate: "2026-06-15", performanceDisclosureScope: "none" as const }; const onlyRefresh = compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-06-20" }, [refresh]); expect(onlyRefresh.performanceInformationCutoff).toBeNull(); expect(onlyRefresh.actualValue).toBeNull(); expect(onlyRefresh.comparisonResult).toBe("insufficient_data"); const result = compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-06-20" }, [refresh, actual(120)]); expect(result.performanceInformationCutoff).toBe("2026-07-01"); expect(result.beforeAnyPerformanceDisclosure).toBe(true); });
  it("retains equal business-node order without suppressing an independent actual comparison", () => {
    const left = { ...snapshot(), id: "a", formedAt: "2026-06-01T07:00:00.000Z", formedAtPrecision: "datetime" as const };
    const right = { ...snapshot(), id: "z", value: 110, formedAt: "2026-06-01T15:00:00+08:00", formedAtPrecision: "datetime" as const };
    const result = buildEarningsExpectationComparisons([right, left], [actual(120)])[0];
    expect(result).toMatchObject({ businessOrderStatus: "equal", comparisonResult: "above", comparabilityStatus: "comparable", absoluteDifference: 10 });
    expect(result.structuredWarningCodes).not.toContain("business_order_equal");
  });
  it("keeps an unresolved historical external source time non-ex-ante", () => {
    const result = compareEarningsExpectation({ ...snapshot(), sourceCategory: "institution_single", sourceName: "测试证券", sourceTitle: "盈利预测", sourceUrl: "https://example.com/report", sourcePublishedAt: "2026-06-01T15:00", sourcePublishedAtPrecision: "datetime", sourcePublishedAtResolution: "unresolved_legacy", sourceVerificationStatus: "verified" }, [actual(120)]);
    expect(result.isExAnte).toBe(false);
    expect(result.performanceDisclosureTimingStatus).toBe("unknown");
    expect(result.nonComparableReasons.some((reason) => reason.includes("原解释时区"))).toBe(true);
  });
  it("recomputes ex-ante status from corrected formedAt in both temporal directions", () => {
    const afterRoot = { ...snapshot(), id: "after-root", asOfDate: "2026-07-02", formedAt: "2026-07-02T01:00:00.000Z", formedAtPrecision: "datetime" as const, formedAtResolution: "absolute" as const };
    const correctedBefore = { ...afterRoot, id: "corrected-before", correctsSnapshotId: "after-root", correctionScope: "value" as const, asOfDate: "2026-06-30", formedAt: "2026-06-30T01:00:00.000Z", createdAt: "2026-07-10T00:00:00.000Z" };
    const before = buildEarningsExpectationComparisons([afterRoot, correctedBefore], [actual(120)])[0];
    expect(before).toMatchObject({ snapshotId: "corrected-before", isExAnte: true, originalBusinessTime: "2026-07-02T01:00:00.000Z", effectiveBusinessTime: "2026-06-30T01:00:00.000Z", temporalCorrectionApplied: true });
    expect(before.correctedTemporalFields).toEqual(expect.arrayContaining(["asOfDate", "formedAt"]));

    const beforeRoot = { ...snapshot(), id: "before-root", asOfDate: "2026-06-30", formedAt: "2026-06-30T01:00:00.000Z", formedAtPrecision: "datetime" as const, formedAtResolution: "absolute" as const };
    const correctedAfter = { ...beforeRoot, id: "corrected-after", correctsSnapshotId: "before-root", correctionScope: "value" as const, asOfDate: "2026-07-02", formedAt: "2026-07-02T01:00:00.000Z", createdAt: "2026-07-10T00:00:00.000Z" };
    const after = buildEarningsExpectationComparisons([correctedAfter, beforeRoot], [actual(120)])[0];
    expect(after).toMatchObject({ snapshotId: "corrected-after", isExAnte: false, originalBusinessTime: "2026-06-30T01:00:00.000Z", effectiveBusinessTime: "2026-07-02T01:00:00.000Z", temporalCorrectionApplied: true });
  });
  it("recomputes external ex-ante status from corrected source publication time and preserves both source values", () => {
    const root = { ...snapshot(), id: "source-root", sourceCategory: "institution_single" as const, sourceName: "测试证券", sourceTitle: "盈利预测", sourceUrl: "https://example.com/report", asOfDate: "2026-06-20", formedAt: "2026-06-20T01:00:00.000Z", formedAtPrecision: "datetime" as const, formedAtResolution: "absolute" as const, sourcePublishedAt: "2026-07-02T01:00:00.000Z", sourcePublishedAtPrecision: "datetime" as const, sourcePublishedAtResolution: "absolute" as const };
    const correction = { ...root, id: "source-correction", correctsSnapshotId: "source-root", correctionScope: "value" as const, sourcePublishedAt: "2026-06-20T00:30:00.000Z", createdAt: "2026-07-10T00:00:00.000Z" };
    root.sourcePublishedAtCalendarDate = "2026-07-02";
    correction.sourcePublishedAtCalendarDate = "2026-06-20";
    const result = buildEarningsExpectationComparisons([correction, root], [actual(120)])[0];
    expect(result).toMatchObject({ isExAnte: true, originalSourcePublishedAt: "2026-07-02T01:00:00.000Z", effectiveSourcePublishedAt: "2026-06-20T00:30:00.000Z", temporalCorrectionApplied: true });
    expect(result.correctedTemporalFields).toContain("sourcePublishedAt");
  });
  it("keeps possible-disclosure boundaries certain only when every possible instant is later", () => {
    const possible = (id: string, publishedAt: string) => ({ ...performancePreview(publishedAt), id, metrics: [], verificationStatus: "metadata_only" as const, parseStatus: "metadata_only" as const, performanceDisclosureScope: "unknown" as const });
    const confirmed = { ...actual(120), publishedAt: "2026-07-01T08:00:00.000Z", eventDate: "2026-07-01" };
    const exactEarly = { ...snapshot(), asOfDate: "2026-06-15", formedAt: "2026-06-15T07:00:00.000Z", formedAtPrecision: "datetime" as const, formedAtResolution: "absolute" as const };
    expect(compareEarningsExpectation(exactEarly, [possible("possible-later", "2026-06-20T08:00:00.000Z"), confirmed]).performanceDisclosureTimingStatus).toBe("before");
    const between = { ...snapshot(), asOfDate: "2026-06-20", formedAt: "2026-06-20T09:00:00.000Z", formedAtPrecision: "datetime" as const, formedAtResolution: "absolute" as const };
    const uncertain = compareEarningsExpectation(between, [possible("possible-earlier", "2026-06-20T08:00:00.000Z"), confirmed]);
    expect(uncertain).toMatchObject({ performanceDisclosureTimingStatus: "unknown", performanceDisclosureUncertain: true, isExAnte: false });
    const onlyPossibleEarly = compareEarningsExpectation(exactEarly, [possible("only-possible", "2026-06-20T08:00:00.000Z")]);
    expect(onlyPossibleEarly).toMatchObject({ performanceDisclosureTimingStatus: "before", performanceDisclosureUncertain: false, isExAnte: true });
    const equal = compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-06-20", formedAt: "2026-06-20T08:00:00.000Z", formedAtPrecision: "datetime", formedAtResolution: "absolute" }, [possible("same", "2026-06-20T08:00:00.000Z")]);
    expect(equal).toMatchObject({ performanceDisclosureTimingStatus: "unknown", performanceDisclosureUncertain: true, isExAnte: false });
    const dateOnly = compareEarningsExpectation({ ...snapshot(), asOfDate: "2026-06-20", formedAt: null, formedAtPrecision: "date", formedAtResolution: "date" }, [possible("same-date", "2026-06-20")]);
    expect(dateOnly).toMatchObject({ performanceDisclosureTimingStatus: "unknown", performanceDisclosureUncertain: true, isExAnte: false });
  });
});

function snapshot(): EarningsExpectationSnapshot { return { id: "s-1", stockId: "demo", market: "A股", reportPeriod: "2026-06-30", periodScope: "half_year", metric: "revenue", estimateShape: "point", value: 100, lowerBound: null, upperBound: null, currency: "CNY", unit: "yuan", accountingBasis: "PRC_GAAP", sourceCategory: "user_estimate", sourceName: "用户个人预测", sourceTitle: "", sourceUrl: null, sourcePublishedAt: null, sourcePublishedAtPrecision: null, sourcePublishedAtResolution: null, sourcePublishedAtTimeZone: null, sourcePublishedAtCalendarDate: null, asOfDate: "2026-06-01", formedAt: null, formedAtPrecision: "date", formedAtResolution: "date", formedAtTimeZone: null, formedAtCalendarDate: "2026-06-01", analystCount: null, institutionCount: null, ingestionMethod: "manual", createdAt: "2026-06-01T00:00:00.000Z", createdBy: "local-user", sourceVerificationStatus: "verified", notes: null, correctsSnapshotId: null, correctionScope: null, schemaVersion: 2 }; }
function actual(value: number | null, periodBasis: "cumulative" | "single_quarter" = "cumulative"): ResearchEvent { return { id: "actual-1", stockId: "demo", stockName: "测试公司", stockCode: "000001.SZ", industryId: "tech", market: "A股", eventType: "financial_update", eventDate: "2026-07-01", publishedAt: "2026-07-01", reportPeriod: "2026-06-30", title: "财务更新", summary: "正式财务", sourceType: "financial_report", sourceName: "正式来源", sourceUrl: "https://example.com/actual", pdfUrl: null, verificationStatus: "verified", parseStatus: "not_applicable", materiality: "high", metrics: [{ key: periodBasis === "single_quarter" ? "singleQuarterOperatingRevenue" : "operatingRevenue", label: "营业收入", value, unit: "CNY", periodBasis, sourceAnnouncementId: null, sourceFinancialPeriod: "2026-06-30" }], relatedAnnouncementIds: [], relatedFinancialPeriod: "2026-06-30", reviewStatus: "not_required", reviewReasons: [], isRestated: false, updatedAt: "2026-07-01" }; }
function performancePreview(publishedAt: string): ResearchEvent { return { ...actual(100), id: "preview-1", eventType: "earnings_preview", sourceType: "announcement", publishedAt, eventDate: publishedAt.slice(0, 10), metrics: [{ key: "operatingRevenueForecastMidpoint", label: "营业收入预告中值", value: 100, unit: "CNY", periodBasis: "range", sourceAnnouncementId: "preview-1", sourceFinancialPeriod: "2026-06-30" }] }; }
