import { describe, it, expect } from 'vitest';
import { canonicalJson } from '../../shared/canonical-json.mjs';
import { portfolioFixture } from './portfolio.fixture';
import { claimTime as at } from './verifiedClaim.fixture';
import { researchExposure, validateLink, linkAt, formalExpressionChoices, validatePortfolioScope } from './portfolio';

describe('Portfolio research exposure', () => {
  it('traces exact Expression → Thesis → Claim → Evidence through original owners', async () => { const f = await portfolioFixture(), r = researchExposure(f.projection.positions[0], f.link, f.owners, at(12)); expect(r.blockers).toEqual([]); expect(r.trace?.revisionId).toBe(f.expression.revisionId); expect(r.trace?.claims[0].ref).toEqual(f.ref); expect(r.trace?.claims[0].evidenceBinding).toEqual(f.claim.binding); expect(formalExpressionChoices(f.owners,at(12))).toHaveLength(1); });
  it('unlinked is unresolved and has no fabricated research percentage', async () => { const f = await portfolioFixture(), r = researchExposure(f.projection.positions[0],null,f.owners,at(12)); expect(r.blockers).toContain('POSITION_UNLINKED'); expect(r).not.toHaveProperty('percentage'); expect(r).not.toHaveProperty('share'); });
  it('superseded Expression does not upgrade historical link', async () => { const f = await portfolioFixture(), bytes=canonicalJson(f.link); f.tick(14); f.repo.saveDraft(f.repo.load().data,{...f.expression, revisionId:'new-expression',supersedes:f.expression.revisionId,createdAt:at(13),asOf:at(13)}); const historical=researchExposure(f.projection.positions[0],f.link,f.owners,at(12)), current=researchExposure(f.projection.positions[0],f.link,f.owners,at(14)); expect(historical.blockers).toEqual([]); expect(current.blockers).toContain('EXPRESSION_UPDATED_REVIEW_REQUIRED'); expect(current.trace?.revisionId).toBe(f.expression.revisionId); expect(canonicalJson(f.link)).toBe(bytes); expect(researchExposure(f.projection.positions[0],{...f.link,asOf:at(14),createdAt:at(14)},f.owners,at(14)).blockers).toContain('EXPRESSION_SUPERSEDED_AT_LINK'); });
  it('Thesis successor propagates review and original invalid authority blocks', async () => { const f=await portfolioFixture(); f.tick(14); f.thesisRepo.saveDraft(f.thesisRepo.load().data,{...f.revision,revisionId:'thesis-successor',supersedes:f.revision.revisionId,createdAt:at(13),asOf:at(13)}); expect(researchExposure(f.projection.positions[0],f.link,f.owners,at(14)).blockers).toContain('THESIS_UPDATED_REVIEW_REQUIRED'); const lost={...f.owners,expressions:()=>{throw Error('THESIS_AUTHORITY_LOST');}}; expect(researchExposure(f.projection.positions[0],f.link,lost,at(14)).blockers).toContain('THESIS_AUTHORITY_LOST'); });
  it('pin drift and foreign position rejected without label matching', async () => { const f=await portfolioFixture(); expect(() => validateLink({...f.link,assetId:'other'})).toThrow(); const bad={...f.link,expression:{...f.link.expression,revisionBytes:canonicalJson({...f.expression,reason:'tampered'})}}; expect(researchExposure(f.projection.positions[0],bad,f.owners,at(12)).blockers).toContain('PORTFOLIO_EXPRESSION_AUTHORITY_UNAVAILABLE'); expect(researchExposure(f.projection.positions[1],f.link,f.owners,at(12)).status).toBe('unresolved'); });
  it('future link and future version fail closed; scope isolated', async () => { const f=await portfolioFixture(); expect(linkAt([f.link],f.link.positionId,at(11))).toBeNull(); expect(() => validatePortfolioScope(f.projection,'real')).toThrow(); expect(researchExposure(f.projection.positions[0],f.link,{...f.owners,scope:'real'},at(12)).blockers).toContain('PORTFOLIO_RESEARCH_SCOPE'); expect(researchExposure(f.projection.positions[0],f.link,{...f.owners,expressions:()=>({...f.owners.expressions(),data:{...f.owners.expressions().data,schemaVersion:'v99'} as never})},at(12)).status).toBe('unresolved'); });
});
