import type { CreatorViewpointData, CreatorSource, ViewpointObservation, ViewpointReview } from '../../types/creatorViewpoint';
import type { ExternalResearchEvent } from '../../types/researchEvent';
import { safeEvidenceUrl } from '../../utils/evidenceUrl';
import { sourceCoverage, observationStatus } from '../../services/creatorViewpoint';

export interface CreatorEvidenceSelection { data: CreatorViewpointData; observation?: ViewpointObservation; source?: CreatorSource; event?: ExternalResearchEvent; review?: ViewpointReview; asOf?: string }
export const stanceLabels = { positive: '积极', neutral: '中性', cautious: '谨慎', negative: '消极', mixed: '混合', unknown: 'unknown' };
export const sourceLabels = { post: '主帖', article: '专栏 / 文章', comment: '评论', self_reply: '本人回复', repost: '转发 / 补充' };
export const relationLabels = { explicit: '本人明确说明因果', inferred: '系统 / 研究者推断', temporal: '仅时间背景相关' };
export function CreatorEvidence({ data, observation, source: selectedSource, event, review, asOf }: CreatorEvidenceSelection) {
  const source = selectedSource ?? data.sources.find(item => item.id === observation?.sourceId);
  const row = (label: string, value: string | null | undefined) => <div className="border-b border-borderSoft py-2"><dt className="text-xs text-textMuted">{label}</dt><dd className="mt-1 whitespace-pre-wrap break-words text-sm">{value || 'unknown'}</dd></div>;
  return <div className="space-y-4 text-textStrong">
    <p className="rounded border border-warning/40 p-3 text-sm text-warning">External Commentary / Creator Viewpoint。审核仅确认观点记录；不代表 Provider Fact、Verified Claim、用户判断或正式 Thesis。</p>
    {event && <section><h3 className="font-semibold">外部事件 · {event.title}</h3><dl>{row('摘要', event.summary)}{row('发生时间', event.eventOccurredAt)}{row('发布时间', event.publishedAt)}{row('录入时间', event.recordedAt)}{row('核验状态', event.verificationStatus)}{row('来源', event.sourceName)}</dl>{safeEvidenceUrl(event.sourceUrl) && <a className="text-cyan underline" href={safeEvidenceUrl(event.sourceUrl)!} target="_blank" rel="noreferrer">打开事件来源</a>}</section>}
    {source && <section><h3 className="font-semibold">原始来源 · {sourceLabels[source.kind]}</h3><dl>{row('作者', data.creators.find(item => item.id === source.creatorId)?.name)}{row('发布时间（精确时刻）', source.publishedAt)}{row('页面时间原文', source.publishedAtLabel)}{row('抓取 / 录入时间', source.capturedAt)}{row('本地记录时间', source.recordedAt)}{row('身份状态', source.authorIdentity)}{row('身份依据', source.identityEvidence)}{row('来源完整性 / 评论覆盖', `${source.completeness} / ${source.commentCoverage}；合并覆盖 ${sourceCoverage(data, source.id)}`)}{row('父级来源', source.parentSourceId)}{row('原文或摘录', source.content)}{row('修订的来源', source.supersedesId)}</dl>{safeEvidenceUrl(source.url) && <a className="text-cyan underline" href={safeEvidenceUrl(source.url)!} target="_blank" rel="noreferrer">打开原始来源</a>}</section>}
    {observation && <section><h3 className="font-semibold">观点记录 · {stanceLabels[observation.stance]}</h3><dl>{row('摘要', observation.summary)}{row('核心理由', observation.reasoning)}{row('条件性判断 / 周期', `${observation.conditional} / ${observation.horizon ?? 'unknown'}`)}{row('Trigger', observation.trigger)}{row('Confirmation', observation.confirmation)}{row('Invalidation', observation.invalidation)}{row('审核状态', observationStatus(data, observation.id, asOf))}{row('录入时间', observation.recordedAt)}{row('修订原因', observation.revisionReason)}{row('修订的观点', observation.supersedesId)}</dl>{observation.eventLinks.map(link => <p className="mt-2 text-sm" key={link.eventId}>{data.events.find(item => item.id === link.eventId)?.title} · {relationLabels[link.relation]} · {link.explanation ?? 'unknown'}</p>)}</section>}
    {review && <section><h3 className="font-semibold">T+{review.offsetDays} 复盘 · calendar days</h3><dl>{row('状态', review.status)}{row('成立条件触发', review.triggerOccurred)}{row('失效条件触发', review.invalidationOccurred)}{row('实际表现', review.actualOutcome)}{row('后续证据', review.evidence)}{row('记录时间', review.recordedAt)}{row('修订的复盘', review.supersedesId)}</dl>{safeEvidenceUrl(review.evidenceUrl) && <a className="text-cyan underline" href={safeEvidenceUrl(review.evidenceUrl)!} target="_blank" rel="noreferrer">打开复盘证据</a>}</section>}
  </div>;
}
