import { useEffect, useMemo, useRef, useState } from 'react';
import { validateProjection, type PortfolioProjection, type Dimension } from '../../../shared/portfolio.mjs';
import type { ThesisWorkspaceDataset } from '../../services/thesisWorkspace';
import type { ChartAuditView } from '../../services/chartAudit';
import type { ClaimBinding } from '../../types/verifiedClaim';
import { createPortfolioResearch, fetchPortfolio } from '../../services/portfolioWorkspace';
import { formalExpressionChoices, linkAt, researchExposure, type PortfolioResearchOwners, type ResearchLink } from '../../services/portfolio';
import { PortfolioRepository, type PortfolioPreview } from '../../services/portfolioRepository';
import { rebalance, targetIdentity, targetPositions, type TargetAllocation } from '../../services/portfolioPlanning';
import { canonicalJson } from '../../../shared/canonical-json.mjs';
import { EvidenceDrawer } from '../research/EvidenceDrawer';
import './portfolio.css';

const accountLifecycle = {active:'启用（active）',inactive:'停用（inactive）',archived:'已归档（archived）'};
const dimensions:Record<Dimension,string>={accountId:'账户',assetId:'资产',assetType:'资产类型',primaryCategory:'主要类别',strategyBucket:'策略分组',currency:'币种'};
const money=(v:number|null,currency:string)=>v===null?'未知':`${v.toLocaleString('zh-CN',{maximumFractionDigits:6})} ${currency}`;
const percent=(v:number|null)=>v===null?'未知':`${(v*100).toFixed(2)}%`;
const defaultClock=()=>new Date();
function saveFile(raw:string) { const u=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='portfolio-planning.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000); }
export function PortfolioWorkspace({dataset}:{dataset:ThesisWorkspaceDataset}) {
  const [research,setResearch]=useState<Awaited<ReturnType<typeof createPortfolioResearch>>|null>(null),[error,setError]=useState(false);
  useEffect(()=>{let active=true;void createPortfolioResearch(dataset,window.localStorage).then(r=>{if(active)setResearch(r);}).catch(()=>{if(active)setError(true);});return()=>{active=false;};},[dataset]);
  const fallback=useMemo<PortfolioResearchOwners>(()=>({scope:'real',expressions(){throw Error('RESEARCH_OWNER_UNAVAILABLE');}}),[]);
  return <PortfolioWorkspacePanel owners={research?.owners??fallback} read={fetchPortfolio} evidence={research?.evidence} researchUnavailable={error} />;
}
export function PortfolioWorkspacePanel({owners,read,evidence,researchUnavailable=false,clock=defaultClock}:{owners:PortfolioResearchOwners;read:(asOf:string)=>Promise<PortfolioProjection>;evidence?:(binding:ClaimBinding)=>ChartAuditView|null;researchUnavailable?:boolean;clock?:()=>Date}) {
  const [projection,setProjection]=useState<PortfolioProjection|null>(null),[asOf,setAsOf]=useState(()=>clock().toISOString()),[problem,setProblem]=useState<string|null>(null),[busy,setBusy]=useState(false);
  const latest=useRef<PortfolioProjection|null>(null);
  const repository=useMemo(()=>new PortfolioRepository(window.localStorage,owners,()=>{if(!latest.current)throw Error('PORTFOLIO_NOT_CONNECTED');return latest.current;},clock),[owners,clock]);
  const [loaded,setLoaded]=useState(()=>repository.load()),[preview,setPreview]=useState<PortfolioPreview|null>(null),[audit,setAudit]=useState<ChartAuditView|null>(null);
  const [positionId,setPositionId]=useState(''),[expressionId,setExpressionId]=useState(''),[rationale,setRationale]=useState('');
  const [cohortKey,setCohortKey]=useState(''),[dimension,setDimension]=useState<TargetAllocation['scope']['dimension']>('assetId'),[accountId,setAccountId]=useState(''),[weights,setWeights]=useState<Record<string,string>>({}),[targetReason,setTargetReason]=useState(''),[reviewNote,setReviewNote]=useState('');
  useEffect(()=>{setLoaded(repository.load());setPreview(null);},[repository]);
  async function refresh(time=asOf) { setBusy(true);try {const p=validateProjection(await read(time));if(p.scope!==owners.scope)throw Error('PORTFOLIO_SCOPE_MISMATCH');latest.current=p;setProjection(p);setProblem(null);return p;}catch(e){latest.current=null;setProjection(null);setProblem(e instanceof Error?e.message:'PORTFOLIO_READ_BLOCKED');throw e;}finally{setBusy(false);} }
  useEffect(()=>{let active=true;setBusy(true);void read(asOf).then(value=>{const p=validateProjection(value);if(active){if(p.scope!==owners.scope)throw Error('PORTFOLIO_SCOPE_MISMATCH');latest.current=p;setProjection(p);setProblem(null);}}).catch(()=>{if(active){latest.current=null;setProjection(null);setProblem('PORTFOLIO_NOT_CONNECTED_OR_BLOCKED');}}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[read,owners.scope]); // Explicit refresh applies the edited asOf.
  const data=loaded.data, now=clock().toISOString();
  let choices:ReturnType<typeof formalExpressionChoices>=[];try{choices=formalExpressionChoices(owners,now);}catch{/* Original authority remains unavailable. */}
  const p=projection, cohort=p?.cohorts.find(c=>canonicalJson([c.currency,c.snapshotDate])===cohortKey);
  const scope=cohort?{currency:cohort.currency,snapshotDate:cohort.snapshotDate,accountId:accountId||null,dimension}:null;
  const members=p&&scope?targetPositions(p,{scope} as TargetAllocation):[];
  const values=[...new Set(members.map(row=>row[dimension]))];
  const targets=data.targets.filter(t=>p && Date.parse(t.createdAt)<=Date.parse(p.asOf) && !data.targets.some(s=>s.supersedes===t.revisionId && Date.parse(s.createdAt)<=Date.parse(p.asOf)));
  const act=(work:()=>void)=>{try{work();setProblem(null);}catch(e){setProblem(e instanceof Error?e.message:'PORTFOLIO_OPERATION_BLOCKED');}};
  function prepareLink() {act(()=>{if(!p)throw Error('PORTFOLIO_NOT_CONNECTED');const row=p.positions.find(r=>r.positionId===positionId),choice=choices.find(c=>c.revision.revisionId===expressionId);if(!row||!choice)throw Error('请选择仓位和正式研究表达');const prior=data.links.filter(l=>l.positionId===positionId).at(-1);const time=clock().toISOString();const link:ResearchLink={linkId:positionId,positionId,accountId:row.accountId,assetId:row.assetId,revisionId:crypto.randomUUID(),supersedes:prior?.revisionId??null,createdAt:time,asOf:time,expression:choice.pin,rationale,approval:{actor:'user',userApprovalRef:crypto.randomUUID(),note:rationale}};setPreview(repository.prepare(data,{kind:'link',value:link}));});}
  function prepareTarget() {act(()=>{if(!scope)throw Error('请选择可比较范围');if(values.some(v=>v===null))throw Error('存在未解析维度');const targetId=targetIdentity(scope),prior=data.targets.filter(t=>t.targetId===targetId).at(-1),time=clock().toISOString();const target:TargetAllocation={targetId,revisionId:crypto.randomUUID(),supersedes:prior?.revisionId??null,createdAt:time,asOf:time,scope,allocations:values.map(v=>{const raw=weights[v!];if(!raw||!/^\d+(\.\d{1,2})?$/.test(raw))throw Error('请填写所有目标比例，最多两位小数');return {value:v!,basisPoints:Math.round(Number(raw)*100)};}),rationale:targetReason,approval:{actor:'user',userApprovalRef:crypto.randomUUID(),note:targetReason}};setPreview(repository.prepare(data,{kind:'target',value:target}));});}
  async function confirm() {if(!preview||!p)return;setBusy(true);try{await refresh(p.asOf);repository.confirm(preview,true);setLoaded(repository.load());setPreview(null);const time=clock().toISOString();setAsOf(time);await refresh(time);}catch(e){setProblem(e instanceof Error?e.message:'PORTFOLIO_CONFIRM_BLOCKED');}finally{setBusy(false);} }
  return <section className="portfolio-workspace" aria-label="组合工作区">
    <header className="portfolio-heading"><div><p className="ui-v2-eyebrow">组合 / Portfolio</p><h1>持仓与研究暴露</h1><p>从正式账本读取持仓，以研究关联解释持有理由，以用户目标形成复核任务。</p></div><span className="portfolio-status">{owners.scope==='synthetic'?'合成能力测试':p?'已连接本机只读投影':'尚未连接组合数据'}</span></header>
    <div className="portfolio-toolbar"><label>查询时点（ISO）<input aria-label="组合查询时点" value={asOf} onChange={e=>setAsOf(e.target.value)} /></label><button className="inbox-action" disabled={busy} onClick={()=>{setPreview(null);void refresh().catch(()=>{});}}>读取组合</button><button className="inbox-action" onClick={()=>saveFile(repository.exportRaw())}>导出研究与规划历史</button></div>
    {loaded.error&&<p role="alert">{loaded.error} 写入已锁定；可导出保留的原始字节。</p>}
    {problem&&<div role="status" className="portfolio-notice"><p>{p?'操作未完成，请检查输入与原始依据。':'本机组合读取尚未连接或被阻断；持仓数量和总额未知。'}</p><details><summary>诊断详情</summary><code>{problem}</code></details></div>}
    {researchUnavailable&&<p className="portfolio-notice">原研究依据暂不可用，研究关联与追溯保持阻断。</p>}
    {!p&&<section className="portfolio-section"><h2>连接本机账本后查看</h2><p>沿用已有账户、资产与正式持仓快照。缺少持仓、估值或投资理由时保持未知。</p><details><summary>本机接入说明</summary><p>仅本机开发服务支持。显式配置 PORTFOLIO_LOCAL_DB 为既有 Local Core 数据库，先运行 npm run local:typecheck 和 npx tsc -p tsconfig.local-core.json，再启动 npm run dev。线上静态页面不接入私人账本。</p></details></section>}
    {p&&<>
      <section className="portfolio-section"><h2>组合状态</h2><p>查询时点：{p.asOf} · {p.status==='conflicted'?'快照冲突，量化结果已阻断':'部分覆盖'} · {p.status==='conflicted'?'仓位数量未知':`${p.positions.length} 个已记录仓位`}</p><p>分母仅为已记录仓位；全账户完整性未证明。不同币种、不同快照日期分开展示，旧快照不作为实时估值。</p><details open={p.status==='conflicted'}><summary>缺失、过期与阻断（{p.blockers.length}）</summary><ul>{p.blockers.map(b=><li key={b}><code>{b}</code></li>)}</ul></details></section>
      <section className="portfolio-section"><h2>结构暴露</h2>{p.cohorts.map(c=><div key={c.currency+c.snapshotDate} className="portfolio-cohort"><h3>{c.currency} · 快照 {c.snapshotDate} · 已记录金额 {money(c.total,c.currency)}</h3>{Object.entries(dimensions).map(([key,label])=><details key={key} open={key==='assetId'}><summary>{label}</summary><div className="portfolio-table-scroll"><table><thead><tr><th>{label}</th><th>快照市值</th><th>范围内占比</th></tr></thead><tbody>{c.exposures.filter(e=>e.dimension===key).map(e=><tr key={e.value??'unknown'}><td>{e.value===null?'未解析':key==='accountId'?p.positions.find(r=>r.accountId===e.value)?.accountName:key==='assetId'?p.positions.find(r=>r.assetId===e.value)?.assetName:e.value}</td><td>{money(e.marketValue,c.currency)}</td><td>{percent(e.share)}</td></tr>)}</tbody></table></div></details>)}</div>)}</section>
      <section className="portfolio-section"><h2>当前持仓与持有依据</h2>{!p.positions.length&&<p>{p.status==='conflicted'?'快照冲突，无法确定持仓。':'没有可展示的合法持仓快照。'}</p>}{p.positions.map(row=>{const link=linkAt(data.links,row.positionId,p.asOf),r=researchExposure(row,link,owners,p.asOf);return <article className="portfolio-position" key={row.positionId}><header><div><h3>{row.assetName}</h3><p>{row.accountName} · 账户状态：{accountLifecycle[row.accountStatus]} · {row.primaryCategory} · {row.strategyBucket??'策略未解析'}</p></div><div>{money(row.marketValue,row.currency)}<p>数量 {row.quantity} · {row.snapshotDate}</p></div></header>{row.accountStatus!=='active'&&<p role="status">该账户{row.accountStatus==='inactive'?'已停用':'已归档'}；持仓仍计入已记录仓位分母，账户状态阻断需复核。</p>}<p>{loaded.error?'本地关联读取失败，持有理由未知。':link?link.rationale:'尚未关联研究表达，持有理由未知。'}</p><p>研究状态：{r.status==='known'?'关系已知':r.status==='partial'?'信息不完整':'待解析或复核'} · {r.expressionUpdated?'Expression 已有后继版本':link?'固定研究版本':'未关联 Expression'} · {r.thesisUpdated?'Thesis 需复核':r.trace?'Thesis 按原始依据校验':'Thesis 未关联或不可用'}</p>{r.relationships.map(rel=><p key={rel.relationshipId}>{rel.macroDriver.id} → {rel.industry.id} · {rel.directness==='direct'?'直接':rel.directness==='indirect'?'间接':'关联未知'} · {rel.rationale}（定性判断）</p>)}<details><summary>版本、证据与计算来源</summary><p>Expression：{link?.expression.revisionId??'未关联'}；Thesis：{r.trace?.thesisRef?.revisionId??'未知'}</p><p>研究表达：{r.trace?.gate.revision.reason??'未知'}</p><p>Thesis：{r.trace?.gate.thesis?.statement??'未知'}</p><p>敏感性：{r.trace?.gate.revision.sensitivity.rationale??'未知'}（定性）</p><p>{[...row.blockers,...r.blockers].join(' / ')||'当前引用可解析'}</p>{r.trace?.claims.map(c=><button className="inbox-action" key={c.ref.revisionId} disabled={!c.usable||!evidence} onClick={()=>act(()=>{const fresh=researchExposure(row,link,owners,p.asOf),claim=fresh.trace?.claims.find(x=>x.ref.revisionId===c.ref.revisionId);if(!claim?.usable||!claim.evidenceBinding||!evidence)throw Error('EVIDENCE_UNAVAILABLE');const view=evidence(claim.evidenceBinding);if(!view)throw Error('EVIDENCE_UNAVAILABLE');setAudit(view);})}>查看原始 Evidence · {c.ref.revisionId}</button>)}<pre>{JSON.stringify({positionId:row.positionId,snapshotId:row.snapshotId,lineage:row.lineage,methodology:p.methodology},null,2)}</pre><p>研究关联历史：{data.links.filter(l=>l.positionId===row.positionId).map(l=>`${l.revisionId} · ${l.createdAt}`).join('；')||'无'}</p></details></article>;})}</section>
      <section className="portfolio-section"><h2>关联持有理由</h2><p>由本人选择 exact 仓位与正式研究表达；关联不代表两个标的是同一证券。</p><div className="portfolio-form"><label>仓位<select value={positionId} onChange={e=>setPositionId(e.target.value)}><option value="">请选择</option>{p.positions.map(row=><option key={row.positionId} value={row.positionId}>{row.accountName} / {row.assetName}</option>)}</select></label><label>正式研究表达<select value={expressionId} onChange={e=>setExpressionId(e.target.value)}><option value="">请选择 exact revision</option>{choices.map(c=><option key={c.revision.revisionId} value={c.revision.revisionId}>{c.revision.reason} · {c.revision.revisionId}</option>)}</select></label><label>关联理由<textarea value={rationale} onChange={e=>setRationale(e.target.value)} /></label></div>{!choices.length&&<p>当前没有可关联的正式研究表达，请在研究页确认 Expression 与上游依据。</p>}<button className="inbox-action" disabled={!!loaded.error||busy||!choices.length} onClick={prepareLink}>预览研究关联</button></section>
      <section className="portfolio-section"><h2>目标配置</h2><p>目标仅覆盖所选快照范围。各项比例须由本人输入，总和为 100%；不提供默认配置。</p><div className="portfolio-form"><label>币种与快照范围<select value={cohortKey} onChange={e=>{setCohortKey(e.target.value);setWeights({});}}><option value="">请选择</option>{p.cohorts.map(c=><option key={c.currency+c.snapshotDate} value={canonicalJson([c.currency,c.snapshotDate])}>{c.currency} / {c.snapshotDate}</option>)}</select></label><label>账户范围<select value={accountId} onChange={e=>{setAccountId(e.target.value);setWeights({});}}><option value="">范围内全部已记录账户</option>{[...new Map(p.positions.map(r=>[r.accountId,r.accountName])).entries()].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>配置维度<select value={dimension} onChange={e=>{setDimension(e.target.value as typeof dimension);setWeights({});}}>{(['accountId','assetId','primaryCategory','strategyBucket'] as const).map(d=><option key={d} value={d}>{dimensions[d]}</option>)}</select></label>{values.map(v=><label key={v??'unknown'}>{v??'未解析'} 目标 %<input aria-label={`${v??'未解析'} 目标比例`} inputMode="decimal" value={weights[v??'']??''} onChange={e=>setWeights({...weights,[v??'']:e.target.value})} /></label>)}<label>配置理由<textarea value={targetReason} onChange={e=>setTargetReason(e.target.value)} /></label></div><button className="inbox-action" disabled={!!loaded.error||busy||!scope} onClick={prepareTarget}>预览目标配置</button><details><summary>配置版本历史（{loaded.error?'未知':data.targets.length}）</summary>{data.targets.map(t=><p key={t.revisionId}>{t.revisionId} · {t.createdAt} · {t.rationale} · {t.allocations.map(a=>`${a.value} ${a.basisPoints/100}%`).join(' / ')}</p>)}</details></section>
      <section className="portfolio-section"><h2>当前与目标 / 再平衡复核</h2><p>这些是规划任务，不会买卖、写入交易或修改持仓。价格、交易单位及完整账户范围未具备，执行保持阻断。</p>{!targets.length&&<p>{loaded.error?'目标配置读取失败，数量未知。':'当前查询时点没有已确认目标，不生成默认再平衡任务。'}</p>}<label>复核说明<input value={reviewNote} onChange={e=>setReviewNote(e.target.value)} /></label>{targets.map(t=>{const task=rebalance(p,t,data.links,owners);const history=data.reviews.filter(r=>r.taskId===task.taskId&&Date.parse(r.createdAt)<=Date.parse(p.asOf));return <article className="portfolio-cohort" key={t.revisionId}><h3>{dimensions[t.scope.dimension]} · {t.scope.currency} · {t.scope.snapshotDate}</h3><p>{t.rationale} · 状态：{history.at(-1)?.status==='reviewed'?'已复核（执行仍阻断）':history.at(-1)?.status==='dismissed'?'已暂缓':'待复核'} · 复核历史 {history.length}</p><div className="portfolio-table-scroll"><table><thead><tr><th>维度值</th><th>当前市值</th><th>当前比例</th><th>目标比例</th><th>差额（百分点）</th></tr></thead><tbody>{task.comparisons.map(c=><tr key={c.value??'unknown'}><td>{c.value??'未知'}</td><td>{money(c.current,t.scope.currency)}</td><td>{percent(c.currentShare)}</td><td>{percent(c.targetShare)}</td><td>{c.delta===null?'未知':(c.delta*100).toFixed(2)}</td></tr>)}</tbody></table></div><details><summary>规划依据与阻断详情</summary><p>{task.blockers.join(' / ')}</p><pre>{JSON.stringify({methodology:task.methodology,lineage:task.lineage,research:task.research},null,2)}</pre>{history.map(r=><p key={r.reviewId}>{r.createdAt} · {r.status} · {r.note}</p>)}</details>{(['reviewed','dismissed'] as const).map(status=><button className="inbox-action" key={status} disabled={!!loaded.error||busy} onClick={()=>act(()=>{setPreview(repository.prepare(data,{kind:'review',value:{reviewId:crypto.randomUUID(),taskId:task.taskId,taskBytes:canonicalJson(task),createdAt:clock().toISOString(),status,actor:'user',userApprovalRef:crypto.randomUUID(),note:reviewNote}}));})}>{status==='reviewed'?'预览复核记录':'预览暂缓记录'}</button>)}</article>;})}</section>
    </>}
    {!loaded.error&&data.reviews.length>0&&<details><summary>全部复核历史（{data.reviews.length}）</summary>{data.reviews.map(r=><article key={r.reviewId}><p>{r.createdAt} · {r.status==='reviewed'?'已复核':r.status==='dismissed'?'已暂缓':'待复核'} · {r.note}</p><details><summary>当时的规划与输入</summary><pre>{JSON.stringify(JSON.parse(r.taskBytes),null,2)}</pre></details></article>)}</details>}
    {preview&&<section className="portfolio-confirm" aria-label="组合确认预览"><h2>确认{preview.kind==='link'?'研究关联':preview.kind==='target'?'目标配置':'复核记录'}</h2><p>仅保存本地研究与规划历史；确认前会重新读取原始依据。</p><pre>{JSON.stringify(preview.value,null,2)}</pre>{preview.blockers.length>0&&<p role="alert">{preview.blockers.join(' / ')}</p>}<button className="inbox-action" disabled={busy||!!preview.blockers.length} onClick={()=>void confirm()}>本人确认保存</button><button className="inbox-action" onClick={()=>setPreview(null)}>取消</button></section>}
    <footer className="portfolio-notice">绩效方法学：未准入。XIRR、TWR、Alpha、归因和年化收益尚未提供。</footer>
    {audit&&<EvidenceDrawer audit={audit} onClose={()=>setAudit(null)} />}
  </section>;
}
