import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { industries } from "../../data/industries";
import { stocks } from "../../data/stocks";
import type { EarningsExpectationComparison, EarningsExpectationSnapshot, ResearchEvent, Stock, WatchItem } from "../../types";
import { buildEarningsExpectationResearchEvents } from "../../services/earningsExpectationEventProvider";
import { buildReviewTasks } from "../../services/reviewTaskProvider";
import { EarningsExpectationCenter } from "./EarningsExpectationCenter";
import { EarningsExpectationFormModal } from "./EarningsExpectationFormModal";
import { EarningsExpectationImportActions, Preview } from "./EarningsExpectationImportModal";
import { StockEarningsExpectationPanel } from "./StockEarningsExpectationPanel";
import { StockDetailDrawer } from "../stock/StockDetailDrawer";

describe("earnings expectation UI and workflow linkage", () => {
  it("51 renders the add-expectation form", () => { const html = renderToStaticMarkup(<EarningsExpectationFormModal stocks={[stock()]} initialStockId="demo" onClose={() => undefined} onSubmit={() => undefined} />); expect(html).toContain("添加业绩预期"); expect(html).toContain("点预测"); });
  it("52 renders correction mode without editing history", () => { const html = renderToStaticMarkup(<EarningsExpectationFormModal stocks={[stock()]} correctionTarget={snapshot()} onClose={() => undefined} onSubmit={() => undefined} />); expect(html).toContain("创建纠正快照"); expect(html).toContain("保存纠正快照"); });
  it("53 renders an append-only revision timeline", () => { const html = centerHtml([{ ...snapshot(), id: "s-0", asOfDate: "2026-05-01", value: 90 }, snapshot()]); expect(html).toContain("修订时间线"); expect(html).toContain("较前值"); });
  it("54 displays the source category", () => expect(centerHtml([snapshot()])).toContain("用户个人预测"));
  it("55 displays ex-ante validity", () => expect(centerHtml([snapshot()], [comparison()])).toContain("事前有效"));
  it("56 displays explicit non-comparability reasons", () => expect(centerHtml([snapshot()], [{ ...comparison(), comparabilityStatus: "not_comparable", comparisonResult: "not_comparable", isExAnte: false, nonComparableReasons: ["会计口径不同或不明确"] }])).toContain("会计口径不同或不明确"));
  it("57 renders the stock-detail earnings expectation module", () => { const sourceStock = stocks[0]; const value = { ...snapshot(), stockId: sourceStock.id, market: sourceStock.market }; const html = renderToStaticMarkup(<StockDetailDrawer stock={sourceStock} stocks={stocks} industries={industries} earningsExpectationSnapshots={[value]} onClose={() => undefined} />); expect(html).toContain("业绩预期"); expect(html).toContain("当前有效预期"); });
  it("58 renders all expectation-center filters", () => { const html = centerHtml([snapshot()]); for (const label of ["公司", "行业", "报告期", "指标", "来源类别", "来源核验", "事前有效", "比较结果", "存在修订", "观察清单"]) expect(html).toContain(label); });
  it("59 generates deterministic full ResearchEvents without duplicates", () => { const first = buildEarningsExpectationResearchEvents([snapshot()], [{ ...comparison(), calculatedAt: "2026-07-02T00:00:00.000Z" }], [stock()]); const second = buildEarningsExpectationResearchEvents([snapshot()], [{ ...comparison(), calculatedAt: "2026-07-10T00:00:00.000Z" }], [stock()]); expect(first).toEqual(second); expect(new Set(first.map((event) => event.id)).size).toBe(first.length); });
  it("60 generates stable de-duplicated ReviewTask IDs", () => { const events = buildEarningsExpectationResearchEvents([snapshot()], [comparison()], [stock()]); const item = watchItem(); const first = buildReviewTasks({ watchItems: [item], events, chains: [], taskStates: [], now: new Date("2026-07-13") }); const second = buildReviewTasks({ watchItems: [item], events: [...events, ...events], chains: [], taskStates: [], now: new Date("2026-07-13") }); expect(first.map((task) => task.id)).toEqual(second.map((task) => task.id)); });
  it("61 never labels a user estimate as institution consensus", () => { const html = renderToStaticMarkup(<StockEarningsExpectationPanel stock={stock()} snapshots={[snapshot()]} financialData={null} announcementData={null} financialLoadStatus="idle" announcementLoadStatus="idle" />); expect(html).toContain("用户个人预测"); expect(html).not.toContain("机构一致预期差"); });
  it("62 never labels a single institution as consensus", () => { const value = { ...snapshot(), sourceCategory: "institution_single" as const, sourceName: "测试证券", sourceTitle: "盈利预测", sourceUrl: "https://example.com/report" }; const html = centerHtml([value]); expect(html).toContain("单家机构预测"); expect(html).not.toContain("机构一致预期差"); });
  it("63 does not emit unsupported institution-surprise wording", () => { const output = [centerHtml([snapshot()], [comparison()]), JSON.stringify(buildEarningsExpectationResearchEvents([snapshot()], [comparison()], [stock()]))].join("\n"); expect(output).not.toContain(["超", "机构", "预期"].join("")); });
  it("64 renders storage errors without a white screen", () => { const html = renderToStaticMarkup(<EarningsExpectationCenter {...centerProps()} snapshots={[]} comparisons={[]} storageError="本地数据已损坏，原始文本未覆盖" />); expect(html).toContain("本地数据已损坏"); expect(html).toContain("业绩预期证据中心"); });
  it("65 keeps narrow-screen layout card-based without page-level horizontal scrolling", () => { const html = centerHtml([snapshot()]); expect(html).toContain("min-w-0"); expect(html).not.toContain("overflow-x-auto"); });
  it("67 emits only a data-warning event for a non-comparable result", () => { const events = buildEarningsExpectationResearchEvents([snapshot()], [{ ...comparison(), comparabilityStatus: "not_comparable", comparisonResult: "not_comparable", isExAnte: false, nonComparableReasons: ["实际值缺失"] }], [stock()]); expect(events.some((event) => event.eventType === "earnings_expectation_data_warning")).toBe(true); expect(events.some((event) => event.eventType === "earnings_expectation_comparison_available")).toBe(false); });
  it("68 applies the configured revision reminder threshold to ReviewTask generation", () => { const first = { ...snapshot(), id: "s-0", value: 100, asOfDate: "2026-05-01", createdAt: "2026-05-01" }; const second = { ...snapshot(), id: "s-2", value: 108, asOfDate: "2026-06-01", createdAt: "2026-06-01" }; const events = buildEarningsExpectationResearchEvents([first, second], [], [stock()], 0.1); const strict = buildReviewTasks({ watchItems: [watchItem()], events, chains: [], taskStates: [], now: new Date("2026-07-13"), expectationRevisionThreshold: 0.1 }); const loose = buildReviewTasks({ watchItems: [watchItem()], events, chains: [], taskStates: [], now: new Date("2026-07-13"), expectationRevisionThreshold: 0.05 }); expect(strict.some((task) => task.ruleType === "earnings_expectation_revision_up")).toBe(false); expect(loose.some((task) => task.ruleType === "earnings_expectation_revision_up")).toBe(true); });
  it("83 disables both import actions when validation fails", () => { const html = renderToStaticMarkup(<EarningsExpectationImportActions preview={invalidPreview()} method="json_import" fileName={null} onImport={() => undefined} />); expect((html.match(/disabled=""/g) ?? [])).toHaveLength(2); expect(html).toContain("合并快照"); expect(html).toContain("替换快照"); });
  it("84 renders mixed CSV as a warning with explicit import and skip counts", () => { const html = renderToStaticMarkup(<Preview value={{ ...invalidPreview(), ok: true, partial: true, totalCount: 2, validCount: 1, addCount: 1, skippedCount: 1, invalidCount: 1 }} />); expect(html).toContain("部分可导入，需二次确认"); expect(html).toContain("将新增：1"); expect(html).toContain("将跳过：1"); });
  it("85 displays basis corrections without a misleading revision rate", () => { const corrected = { ...snapshot(), id: "s-2", correctsSnapshotId: "s-1", correctionScope: "basis" as const, unit: "hundred_million_yuan" as const, value: 1 }; const html = centerHtml([snapshot(), corrected]); expect(html).toContain("口径纠正"); expect(html).toContain("未计算修订率"); });
  it("86 exposes both timing judgments in the center", () => { const html = centerHtml([snapshot()], [comparison()]); expect(html).toContain("早于实际值披露：是"); expect(html).toContain("早于任何同指标业绩信息：是"); });
  it("91 keeps an acknowledged comparison task stable after reload and recalculation", () => { const item = watchItem(); const firstEvents = buildEarningsExpectationResearchEvents([snapshot()], [{ ...comparison(), calculatedAt: "2026-07-02T00:00:00.000Z" }], [stock()]); const first = buildReviewTasks({ watchItems: [item], events: firstEvents, chains: [], taskStates: [], now: new Date("2026-07-13") }).find((task) => task.ruleType === "earnings_expectation_comparison"); expect(first).toBeDefined(); const state = { taskId: first!.id, status: "acknowledged" as const, acknowledgedAt: "2026-07-03", dismissedAt: null, snoozedUntil: null, updatedAt: "2026-07-03" }; const reloadedEvents = buildEarningsExpectationResearchEvents([snapshot()], [{ ...comparison(), calculatedAt: "2026-07-10T00:00:00.000Z" }], [stock()]); const reloaded = buildReviewTasks({ watchItems: [item], events: reloadedEvents, chains: [], taskStates: [state], now: new Date("2026-07-13") }).find((task) => task.ruleType === "earnings_expectation_comparison"); expect(reloaded?.id).toBe(first?.id); expect(reloaded?.createdAt).toBe(first?.createdAt); expect(reloaded?.status).toBe("acknowledged"); });
});

function centerHtml(values: EarningsExpectationSnapshot[], comparisons: EarningsExpectationComparison[] = []) { return renderToStaticMarkup(<EarningsExpectationCenter {...centerProps()} snapshots={values} comparisons={comparisons} />); }
function centerProps() { return { snapshots: [] as EarningsExpectationSnapshot[], comparisons: [] as EarningsExpectationComparison[], importHistory: [], stocks: [stock()], industries: [{ id: "tech", name: "科技", segments: [] }] as never[], watchItems: [watchItem()], onAdd: () => undefined, onCorrect: () => undefined, onImport: () => undefined, onOpenStock: () => undefined }; }
function stock() { return { id: "demo", name: "测试公司", code: "000001.SZ", market: "A股", industryId: "tech", segmentId: "segment", dataMode: "mixed" } as Stock; }
function snapshot(): EarningsExpectationSnapshot { return { id: "s-1", stockId: "demo", market: "A股", reportPeriod: "2026-06-30", periodScope: "half_year", metric: "revenue", estimateShape: "point", value: 100, lowerBound: null, upperBound: null, currency: "CNY", unit: "yuan", accountingBasis: "PRC_GAAP", sourceCategory: "user_estimate", sourceName: "用户个人预测", sourceTitle: "", sourceUrl: null, sourcePublishedAt: null, asOfDate: "2026-06-01", analystCount: null, institutionCount: null, ingestionMethod: "manual", createdAt: "2026-06-01T00:00:00.000Z", createdBy: "local-user", sourceVerificationStatus: "verified", notes: null, correctsSnapshotId: null, schemaVersion: 1 }; }
function comparison(): EarningsExpectationComparison { return { id: "c-1", snapshotId: "s-1", actualEventId: "actual-1", stockId: "demo", reportPeriod: "2026-06-30", periodScope: "half_year", metric: "revenue", expectedValue: 100, expectedLowerBound: null, expectedUpperBound: null, actualValue: 120, absoluteDifference: 20, relativeDifference: 0.2, comparisonResult: "above", comparisonMethod: "点预测：实际值减预期值", isExAnte: true, beforeActualDisclosure: true, beforeAnyPerformanceDisclosure: true, actualDisclosureAt: "2026-07-01T08:00:00.000Z", performanceInformationCutoff: "2026-07-01T08:00:00.000Z", comparisonAvailableAt: "2026-07-01T08:00:00.000Z", comparabilityStatus: "comparable", nonComparableReasons: [], calculatedAt: "2026-07-01" }; }
function watchItem(): WatchItem { return { id: "watch-1", stockId: "demo", createdAt: "2026-05-01", updatedAt: "2026-05-01", status: "观察", priority: "high", tags: [], reason: "跟踪", thesis: "假设", validationCriteria: [], riskCriteria: [], nextReviewAt: null, lastReviewedAt: null, archivedAt: null, source: "user", schemaVersion: 2 }; }
function invalidPreview() { return { ok: false, partial: false, schemaVersion: 1, totalCount: 0, validCount: 0, addCount: 0, skippedCount: 0, duplicateCount: 0, conflictCount: 0, invalidCount: 1, issues: [{ row: 0, code: "invalid", message: "无效" }], snapshots: [] }; }
