import type { AShareAnnouncementData, AShareFinancialData, FinancialDerivedMetrics, FinancialPeriodMetrics, FinancialReport, Industry, MacroIndicator, ResearchEvent, ResearchEventSnapshot, ReviewEntry, ReviewTask, Stock, WatchItem, EarningsExpectationSnapshot } from "../types";
import type { CompanyPresentationDetails } from "../components/stock/StockDetailDrawer";
import { UI_REVIEW_LABEL, type UiReviewProfile } from "./config";

// Deliberately authored here; never imported from the production dataset/registry.
export const REVIEW_AT = "2026-09-09T10:00:00+08:00";
export const REVIEW_NOW = new Date(REVIEW_AT);
const quality = { source: UI_REVIEW_LABEL, sourceEndpoint: "synthetic-price-history", status: "mock" as const };
const missingChange = { value: null, changeAmount: null, reason: "missing_value" as const, baseSign: null };
const derived: FinancialDerivedMetrics = { revenueYoY: missingChange, revenueQoQ: missingChange, parentNetProfitYoY: missingChange, parentNetProfitQoQ: missingChange, deductedNetProfitYoY: missingChange, deductedNetProfitQoQ: missingChange, grossMargin: .3, netMargin: .12, operatingCashFlowToNetProfit: null, receivablesToRevenue: null, inventoryToRevenue: null, debtToAssetRatio: .35, researchExpenseRatio: .08 };
function metrics(revenue: number, profit: number, cash: number): FinancialPeriodMetrics {
  return { operatingRevenue: revenue, operatingCost: revenue * .7, operatingProfit: profit, totalProfit: profit, netProfit: profit, netProfitAttributableToParent: profit, netProfitExcludingNonRecurring: profit, researchAndDevelopmentExpense: revenue * .08, sellingExpense: null, administrativeExpense: null, financialExpense: null, netOperatingCashFlow: cash, cashReceivedFromSales: null, cashPaidForGoodsAndServices: null, capitalExpenditure: null, netInvestingCashFlow: null, netFinancingCashFlow: null };
}
function financial(stock: Stock): AShareFinancialData {
  const reports: FinancialReport[] = ["2025-09-30", "2025-12-31", "2026-03-31", "2026-06-30"].map((period, i) => ({
    stockCode: stock.code, market: "unknown", companyName: stock.name, reportPeriod: period, reportType: (["Q3", "FY", "Q1", "H1"] as const)[i], fiscalYear: i < 2 ? 2025 : 2026, fiscalQuarter: [3,4,1,2][i], announcementDate: "2026-08-28", statementScope: "consolidated", currency: "CNY", unit: "yuan", sourceUnit: "元", normalizedUnit: "元", normalizationFactor: 1,
    status: "partial", errorCode: null, errorMessage: null, isRestated: false, isDerived: false, derivationMethod: null, sourcePeriods: [], rawFieldCoverage: { available: 10, total: 30 }, coreFieldCoverage: { available: 4, total: 4 }, fieldStatus: {},
    cumulative: metrics((i+1)*300_000_000, (i+1)*36_000_000, (i+1)*28_000_000), singleQuarter: metrics(300_000_000+i*28_000_000, i===1 ? -12_000_000 : 36_000_000+i*5_000_000, i===0 ? -8_000_000 : 30_000_000),
    balanceSheet: { totalAssets: 2_400_000_000, totalLiabilities: 840_000_000, equityAttributableToParent: 1_560_000_000, cashAndCashEquivalents: 260_000_000, accountsReceivable: 140_000_000, notesReceivable: null, contractAssets: null, inventory: 90_000_000, accountsPayable: null, contractLiabilities: null, shortTermBorrowings: null, longTermBorrowings: null, goodwill: 0 }, derived, auditStatus: UI_REVIEW_LABEL,
    provider: UI_REVIEW_LABEL, providerVersion: "ui-review-v1", sourceDescription: UI_REVIEW_LABEL, sourceUrl: "", sourceIdentifier: `ui-review-${period}`, fetchedAt: REVIEW_AT, sourceUpdatedAt: null, generatedAt: REVIEW_AT,
  }));
  return { schemaVersion: "1.0.0", id: stock.id, stockCode: stock.code, market: "unknown", companyName: stock.name, industryType: "general", status: "partial", errorCode: null, errorMessage: null, provider: UI_REVIEW_LABEL, providerVersion: "ui-review-v1", fetchedAt: REVIEW_AT, generatedAt: REVIEW_AT, lastSuccessfulFetchAt: null, currentFetchError: null, reports: reports.reverse(), quality };
}
function announcementData(stock: Stock): AShareAnnouncementData {
  return { schemaVersion: "1.0.0", stockId: stock.id, stockCode: stock.code, companyName: stock.name, market: "A股", provider: UI_REVIEW_LABEL, providerVersion: "ui-review-v1", generatedAt: REVIEW_AT, fetchedAt: REVIEW_AT, lastSuccessfulFetchAt: null, currentFetchError: null, status: "partial", dateRange: { start: "2026-08-01", end: "2026-09-09" }, quality,
    announcements: [1,2,3].map(i=>({ schemaVersion: "1.0.0", announcementId: `${stock.id}-announcement-${i}`, stockId: stock.id, stockCode: stock.code, companyName: stock.name, market: "A股", title: `样例公告 ${i} · 报告与经营资料`, rawTitle: `样例公告 ${i}`, category: "other", subcategory: null, classificationConfidence: "low", classificationEvidence: [UI_REVIEW_LABEL], announcementDate: `2026-09-0${i+3}`, announcementTime: null, reportPeriod: null, sourceProvider: UI_REVIEW_LABEL, sourceDescription: UI_REVIEW_LABEL, officialUrl: null, pdfUrl: null, fetchedAt: REVIEW_AT, sourceUpdatedAt: null, status: "partial", parseStatus: "metadata_only", parseErrorCode: null, parseErrorMessage: null, isCorrection: false, correctedAnnouncementId: null, isCancelled: false, isDuplicate: false, duplicateOf: null, supersededBy: null, performanceForecastEvents: [], performanceExpressEvent: null, periodicReportEvent: null, reasonSummary: UI_REVIEW_LABEL, reasonItems: [], announcementParsingResult: { status: "metadata_only", method: "synthetic", confidence: "low", evidenceCount: 0 } })) };
}
export function createReviewFixtures(profile: UiReviewProfile) {
  const empty = profile === "empty";
  const degraded = profile === "degraded";
  const industries: Industry[] = ["先进制造", "数字基础设施"].map((name,i)=>({ id: `ui-review-industry-${i}`, name: `样例${name}`, prosperity: "中", stage: "景气上行", drivers: ["合成资料：需求结构变化", "合成资料：产能与交付节奏"], catalysts: ["样例：报告期经营数据披露"], risks: ["合成资料无研究效力；下游需求与交付存在不确定性"], styles: ["价值", "主题"], chain: [{ stage: "上游", items: ["样例材料", "样例设备"] }, { stage: "中游", items: ["样例制造", "样例系统"] }, { stage: "下游", items: ["样例应用"] }], segments: [0,1].map(j=>({ id: `ui-review-segment-${i}-${j}`, industryId: `ui-review-industry-${i}`, name: `样例细分 ${j+1}`, logic: "界面验收：需求、竞争与交付构成研究框架。", demandSource: "样例终端需求", supplyPattern: "样例供给格局", moat: "样例工艺与验证周期", trend: "合成资料，不代表真实产业趋势", keyVariables: ["交付节奏", "研发投入", "客户验证"], stockIds: [0,1,2].map(k=>`ui-review-company-${i*3+k+1}`) })) }));
  const stocks: Stock[] = Array.from({length:6},(_,i)=>({
    id: `ui-review-company-${i+1}`, name: degraded && i===0 ? "样例星河先进制造与数字基础设施联合技术股份有限公司（超长名称验收）" : ["样例星河制造", "样例远川设备", "样例澄海材料", "样例云岭科技", "样例方舟系统", "样例光原组件"][i], code: `DEMO${i+1}`, market: i===5 ? "港股" : "A股", industryId: industries[Math.floor(i/3)].id, segmentId: industries[Math.floor(i/3)].segments[i%2].id, leaderPosition: "合成研究对象", business: empty ? "尚无公司经营资料。" : "界面验收样例：为下游提供核心组件、配套设备与技术服务，收入来自产品交付及维护。", thesis: empty ? "尚无研究依据。" : "合成研究依据：观察交付节奏、产品结构与经营现金流能否同步改善。该文本不对应任何真实公司或投资判断。",
    financial: { revenue: "样例 12 亿元", netProfit: "样例 1.44 亿元", grossMargin: "样例 30%", netMargin: "样例 12%", roe: "样例 9%", debtRatio: "样例 35%", operatingCashFlow: "样例 1.12 亿元", revenueGrowth: "待核验", profitGrowth: "待核验", marketCap: "样例 48 亿元" }, valuation: { pe: empty ? "暂缺" : "样例 24.5", pb: empty ? "暂缺" : "样例 2.8", ps: empty ? "暂缺" : "样例 4.0" }, growthDrivers: ["合成增长资料"], risks: [UI_REVIEW_LABEL, "样例：交付延期和研发支出变化"], trackingMetrics: ["交付变化", "现金流与利润差异", "客户验证进度"], riskLevel: "高", chainPosition: "中游", evidenceLevel: "低", verificationStatus: "待验证", themeTags: ["合成数据", "界面验收"],
    evidenceItems: empty ? [] : [{ id: `ui-review-evidence-${i}`, claim: "样例：业务关系仍需查证", sourceType: "其他", sourceName: UI_REVIEW_LABEL, sourceDate: "2026-09-07", confidence: "低", verificationStatus: "待验证" }],
    quote: { id: `ui-review-company-${i+1}`, latestPrice: empty || (degraded && i===1) ? null : 42.6+i*3, pctChange: empty ? null : i%2 ? -2.6 : 1.8, marketCap: empty ? null : 4_800_000_000, pe: null, pb: null, updatedAt: degraded ? "2025-01-01" : REVIEW_AT, quality: { ...quality, status: empty ? "missing" : degraded ? "stale" : "mock" } },
    priceHistory: empty ? [] : Array.from({length:40},(_,j)=>({ date: new Date(Date.UTC(2026,6,1+j)).toISOString().slice(0,10), close: degraded && j%7===0 ? null : Math.round((38+i*3+j*.12+Math.sin(j*.55)*2)*100)/100, amount: null, pctChange: null })), dataQuality: [quality], missingFields: empty ? ["priceHistory", "financials"] : degraded ? ["sourcePublishedAt", "financials"] : [],
    researchProfile: { validationSignals: ["核验收入与现金流", "核验订单转化", "查证来源与发布时间"], businessBreakdown: [{ name: "核心组件（样例）", description: "合成业务资料：产品交付与后续维护。", revenueDriver: "样例交付数量", marginDriver: "样例产品结构" }] },
  }));
  // Empty still exposes one explicitly empty company for all five chapter checks.
  const companies = empty ? stocks.slice(0,1) : stocks;
  const details: Record<string, CompanyPresentationDetails> = {};
  for (const stock of companies) {
    const data = !empty && !(degraded && stock===companies[0]) ? financial(stock) : null;
    const announcements = !empty ? announcementData(stock) : null;
    if (data) stock.aShareFinancialSummary = { ...data, latestReportPeriod: "2026-06-30", latestReportType: "H1", latestSingleQuarter: data.reports[0].singleQuarter!, latestChanges: derived, latestRatios: derived, latestBalanceSheet: data.reports[0].balanceSheet, fieldStatus: {}, detailPath: "" };
    if (announcements) stock.aShareAnnouncementSummary = { ...announcements, announcementCount: 3, categoryCounts: { other:3 }, latestAnnouncementDate: "2026-09-06", latestPerformanceAnnouncementDate: null, recentAnnouncements: announcements.announcements, latestPerformanceAnnouncement: null, detailPath: "" };
    details[stock.id] = { stockId: stock.id, financial: data, announcements, status: empty ? "idle" : degraded && stock===companies[0] ? "error" : "success" };
  }
  const watchItems: WatchItem[] = empty ? [] : companies.slice(0,3).map((stock,i)=>({ id: `ui-review-watch-${i}`, stockId: stock.id, createdAt: REVIEW_AT, updatedAt: REVIEW_AT, status: "等业绩验证", priority: i===0 ? "high" : "medium", tags: ["合成数据"], reason: "样例：观察经营变化与披露证据", thesis: "合成假设：交付变化需要后续资料验证。", validationCriteria: ["样例收入与现金流同步变化"], riskCriteria: ["样例交付持续延后"], nextReviewAt: "2026-09-08", lastReviewedAt: "2026-08-01", archivedAt: null, source: "sample", schemaVersion: 2 }));
  const events: ResearchEvent[] = empty ? [] : Array.from({length:8},(_,i)=>({ id: `ui-review-event-${i}`, stockId: companies[i%companies.length].id, stockName: companies[i%companies.length].name, stockCode: companies[i%companies.length].code, industryId: companies[i%companies.length].industryId, market: companies[i%companies.length].market, eventType: degraded ? "data_warning" : "periodic_report", eventDate: `2026-09-0${8-i}`, publishedAt: null, reportPeriod: "2026-06-30", title: ["样例半年报：经营资料待复核", "样例现金流与利润差异", "样例交付进度更新", "样例公告来源核验"][i%4], summary: UI_REVIEW_LABEL+"。用于核对事件列表、来源状态与公司研究跳转。", sourceType: "announcement", sourceName: UI_REVIEW_LABEL, sourceUrl: null, pdfUrl: null, verificationStatus: degraded ? "error" : "verified", parseStatus: degraded ? "metadata_only" : "parse_success", materiality: "medium", metrics: [{ key: "netProfitAttributableToParent", label: "样例归母净利润", value: degraded ? null : 144_000_000, unit: "CNY", periodBasis: "cumulative", sourceAnnouncementId: null, sourceFinancialPeriod: "2026-06-30" }], performanceDisclosureScope: "listed_metrics", relatedAnnouncementIds: [], relatedFinancialPeriod: "2026-06-30", reviewStatus: "pending", reviewReasons: [degraded ? "合成场景：来源索引失败，仅元数据，数值不可比" : "合成场景：需要人工核验"], isRestated: null, updatedAt: REVIEW_AT }));
  const tasks: ReviewTask[] = watchItems.map((item,i)=>({ id: `ui-review-task-${i}`, watchItemId: item.id, ruleType: "due_review", relatedEventIds: [events[i].id], createdAt: REVIEW_AT, dueAt: "2026-09-09", severity: i===0 ? "high" : "medium", title: ["复核经营数据", "查证来源与时间", "更新下一次验证条件"][i], description: "界面验收：按既有资料检查，不形成研究结论。", status: "pending", acknowledgedAt: null, dismissedAt: null, snoozedUntil: null }));
  const reviewEntries: ReviewEntry[] = watchItems.map((item,i)=>({ id: `ui-review-entry-${i}`, watchItemId: item.id, createdAt: "2026-08-01T10:00:00+08:00", triggerType: "manual", triggerEventIds: [], beforeSnapshot: { status: "观察", thesis: "样例旧假设", validationCriteria: [], riskCriteria: [] }, afterSnapshot: { status: item.status, thesis: item.thesis, validationCriteria: item.validationCriteria, riskCriteria: item.riskCriteria }, summary: "合成历史复盘：保留旧判断", rationale: UI_REVIEW_LABEL, evidenceRefs: [], decision: "继续观察（样例）", nextReviewAt: item.nextReviewAt, correctsReviewEntryId: null }));
  const expectations: EarningsExpectationSnapshot[] = empty ? [] : [0,1,2].map(i=>({ id: `ui-review-expectation-${i}`, stockId: companies[0].id, market: "A股", reportPeriod: "2026-06-30", periodScope: "half_year", metric: "attributable_net_profit", estimateShape: "range", value: null, lowerBound: 120_000_000+i*10_000_000, upperBound: 160_000_000+i*10_000_000, currency: "CNY", unit: "yuan", accountingBasis: "PRC_GAAP", sourceCategory: i===2 ? "institution_single" : "user_estimate", sourceName: i===2 ? "样例研究机构（合成）" : "样例用户判断（合成）", sourceTitle: UI_REVIEW_LABEL, sourceUrl: null, sourcePublishedAt: degraded ? null : `2026-07-0${i+1}`, sourcePublishedAtPrecision: "date", sourcePublishedAtResolution: "date", asOfDate: `2026-07-0${i+1}`, formedAt: `2026-07-0${i+1}`, formedAtPrecision: "date", formationTimeBasis: "actual", analystCount: null, institutionCount: null, ingestionMethod: "manual", createdAt: REVIEW_AT, createdBy: "ui-review-synthetic", sourceVerificationStatus: degraded ? "pending" : "verified", notes: UI_REVIEW_LABEL, correctsSnapshotId: null, schemaVersion: 2 }));
  const snapshot: ResearchEventSnapshot = { events, chains: empty ? [] : [{ id: "ui-review-chain", stockId: companies[0].id, stockName: companies[0].name, stockCode: companies[0].code, reportPeriod: "2026-06-30", preview: [], revision: [], flash: [], formal: [events[0]], financialUpdates: [], missingStages: ["preview", "revision", "flash"], differences: [], hasMaterialDifference: false, needsReview: true }], generatedAt: REVIEW_AT };
  const macro: MacroIndicator[] = empty ? [] : [{ id: "ui-review-macro", category: "宏观环境", name: "样例宏观观测", currentStatus: UI_REVIEW_LABEL, trend: "待验证", marketImpact: "不形成方向判断", trackingIndicators: ["样例观测"], metrics: ["PMI", "CPI", "M2", "LPR"].map((label,i)=>({ label, value: degraded && i===0 ? "" : ["50.2", "0.8", "7.1", "3.0"][i], note: UI_REVIEW_LABEL, source: UI_REVIEW_LABEL, updatedAt: degraded ? undefined : "2026-08-31", status: degraded ? "partial" : "mock" })) }];
  return { companies, industries: empty ? [] : industries, watchItems, tasks, reviewEntries, snapshot, expectations, macro, details };
}
